<?php


class PageController extends CController
{


    public function __construct($slug, $layout = '')
    {
        parent::__construct();

        $this->_slug = $slug;
        if ($layout) {
            $this->_layout = $layout . '.php';
        }

        $this->_data = CFrontPage::GetDatas($this->_slug);

        $this->_uID = $this->_data['pid'];

        self::$_menuElemID = $this->_data['pid'];

        if (!$this->_data) {
            $redirect_check = CStdRedirects::GetRedirect($this->_slug, self::$_contextID);
            if ($redirect_check !== false) {
                header('Location: ' . $redirect_check);
                die;
            } else {
                $this->not_found();
            }
        }
        $this->seo = CFrontSeo::GetDatas($this->_data['page_seo']);
        self::$_breadcrumb = [
            ['type' => 'home', 'label' => CDictionaryUser::GetKey('home'), 'id' => null, 'active' => false],
            ['type' => 'page', 'label' => $this->_data['page_title'], 'id' => null, 'active' => true],
        ];
    }

    public function start()
    {
        if (file_exists(self::$_controller->_viewDir . DIRECTORY_SEPARATOR . self::$_controllerID . '/page-' . $this->_data['pid'] . '.php')) {
            $this->_viewFile = '/page-' . $this->_data['pid'] . '.php';
        }
        return parent::start(); // TODO: Change the autogenerated stub
    }

}